version: "3"

services:
  wetty:
    build: .
    image: rgeve/wetty:latest
    container_name: wetty
    tty: true
    working_dir: /app
    volumes:
      - ./termdata:/app/termdata
      - ./public:/app/public
    ports:
      - "8088:3000"
    environment:
      PORT: 3000
